### PR TITLE
Revert "use rapidfuzz instead of fuzzywuzzy"

### PR DESCRIPTION
**Pull request by philsMINT**
Reverts ag-gipp/AnnoMathTeX#6

### CODE REVIEW

**Comment by maxbachmann** [comment]
Did something not work?

**Comment by philsMINT** [comment]
Yes, there were problems: from rapidfuzz import fuzz, utils - ImportError: DLL load failed.
I assume the C-backend needs the Visual C++ Redistributable under Windows?

**Comment by maxbachmann** [comment]
Thanks for the feedback.
Yes it does require the Visual C++ 2019 redistributable (includes C++ 2015 and 2017) on Windows to find the C++ library. (https://maxbachmann.github.io/rapidfuzz/installation/)

**Comment by philsMINT** [comment]
Done, now it's working, thank you!

**Pull request merged**
